"use server";
import { redirect } from "next/navigation"; import { revalidatePath } from "next/cache"; import { createClient } from "@/lib/supabase/server"; import { getCurrentContext } from "@/lib/auth";
import { advertiserSchema,campaignSchema,loginSchema,reservationSchema,signupSchema,type ActionState } from "@/lib/validation"; import { canManageFirstSlice,getAuthCallbackUrl,safeErrorMessage } from "@/lib/security";
const fields=(f:FormData)=>Object.fromEntries(f.entries()); const report=(op:string,e:unknown):ActionState=>{console.error(`${op} failed`,e);return{message:safeErrorMessage(e)}};
export async function login(_:ActionState,f:FormData):Promise<ActionState>{const p=loginSchema.safeParse(fields(f));if(!p.success)return{errors:p.error.flatten().fieldErrors,message:"Review the sign-in details."};const s=await createClient();const{error}=await s.auth.signInWithPassword(p.data);if(error){console.error("Login failed",{code:error.code});return{message:"Unable to sign in. Check your credentials and try again."}}redirect("/dashboard")}
export async function signup(_:ActionState,f:FormData):Promise<ActionState>{const p=signupSchema.safeParse(fields(f));if(!p.success)return{errors:p.error.flatten().fieldErrors,message:"Review the account details."};try{const s=await createClient();const{error}=await s.auth.signUp({...p.data,options:{emailRedirectTo:getAuthCallbackUrl()}});if(error){console.error("Signup failed",{code:error.code});return{message:"Unable to create the account. Check the form and try again."}}return{success:true,message:"If the account can be created, check your email for the next step."}}catch(e){return report("Signup",e)}}
export async function signout(){const s=await createClient();await s.auth.signOut();redirect("/login")}
export async function createOrganization(_:ActionState,f:FormData):Promise<ActionState>{const s=await createClient();const{error}=await s.rpc("create_organization_with_owner",{org_name:String(f.get("name"))});if(error)return report("Organization creation",error);redirect("/dashboard")}
export async function setActiveOrganization(_:ActionState,f:FormData):Promise<ActionState>{const id=String(f.get("organizationId"));if(!/^[0-9a-f-]{36}$/i.test(id))return{message:"Select a valid organization."};const s=await createClient();const{error}=await s.rpc("set_active_organization",{org_id:id});if(error)return report("Organization selection",error);redirect("/dashboard")}
export async function createAdvertiser(_:ActionState,f:FormData):Promise<ActionState>{const p=advertiserSchema.safeParse(fields(f));if(!p.success)return{errors:p.error.flatten().fieldErrors,message:"Review the highlighted fields."};try{const{supabase,organizationId,membership}=await getCurrentContext();if(!canManageFirstSlice(membership.role))return{message:"You are not authorized to create advertisers."};const d=p.data;const{error}=await supabase.rpc("create_advertiser_with_details",{org_id:organizationId,payload:{name:d.businessName,category:d.category,contact_name:d.contactName,email:d.email,phone:d.phone,address_line_1:d.addressLine1,address_line_2:d.addressLine2,city:d.city,state:d.state,postal_code:d.postalCode}});if(error)return report("Advertiser creation",error)}catch(e){return report("Advertiser creation",e)}revalidatePath("/advertisers");redirect("/advertisers?created=1")}
export async function createCampaign(_:ActionState,f:FormData):Promise<ActionState>{const p=campaignSchema.safeParse({...fields(f),categoryExclusivity:f.get("categoryExclusivity")==="on"});if(!p.success)return{errors:p.error.flatten().fieldErrors,message:"Review the campaign details."};const{supabase,organizationId,membership}=await getCurrentContext();if(!canManageFirstSlice(membership.role))return{message:"You are not authorized to create campaigns."};const d=p.data;const{data,error}=await supabase.rpc("create_campaign_with_slots",{org_id:organizationId,payload:{name:d.name,territory:d.territory,product_type:d.productType,publication_date:d.publicationDate,sales_deadline:d.salesDeadline,artwork_deadline:d.artworkDeadline,proof_deadline:d.proofDeadline,print_deadline:d.printDeadline,mailing_quantity:d.mailingQuantity,estimated_printing_cost_cents:d.estimatedPrintingCost,estimated_postage_cost_cents:d.estimatedPostageCost,slot_count:d.slotCount,standard_slot_price_cents:d.standardSlotPrice,category_exclusivity_enabled:d.categoryExclusivity}});if(error)return report("Campaign creation",error);redirect(`/campaigns/${data}`)}
export async function reserveSlot(_:ActionState,f:FormData):Promise<ActionState>{const p=reservationSchema.safeParse(fields(f));if(!p.success)return{errors:p.error.flatten().fieldErrors,message:"Review the reservation."};const{supabase,organizationId,membership}=await getCurrentContext();if(!canManageFirstSlice(membership.role))return{message:"You are not authorized to reserve campaign slots."};const{data,error}=await supabase.rpc("reserve_campaign_slot",{org_id:organizationId,slot_id:p.data.slotId,advertiser_id:p.data.advertiserId,sale_price_cents:p.data.salePrice});if(error)return report("Reservation",error);const result=Array.isArray(data)?data[0]:data;if(!result?.campaign_id)return{message:"The reservation completed but its campaign could not be refreshed."};revalidatePath(`/campaigns/${result.campaign_id}`);return{success:true,message:"Slot reserved."}}
