import { notFound } from "next/navigation";
import { ApplicationHeader } from "@/components/application-shell/application-header";
import { PageContainer } from "@/components/application-shell/page-container";
import { ReserveForm } from "@/components/campaigns/reserve-form";
import { getCurrentContext } from "@/lib/auth";
import { formatCurrency } from "@/lib/money";
import { requireQueryData } from "@/lib/query";
import { canManageFirstSlice } from "@/lib/security";
export default async function CampaignDetail({params}:{params:Promise<{campaignId:string}>}){
 const{campaignId}=await params;const{supabase,organizationId,membership}=await getCurrentContext();const canManage=canManageFirstSlice(membership.role);
 const[cr,sr,ar,pr]=await Promise.all([supabase.from("campaigns").select("*").eq("organization_id",organizationId).eq("id",campaignId).maybeSingle(),supabase.from("campaign_slots").select("*").eq("organization_id",organizationId).eq("campaign_id",campaignId).order("identifier"),supabase.from("advertisers").select("id,name").eq("organization_id",organizationId).eq("status","active").order("name"),supabase.from("placements").select("campaign_slot_id,sale_price_cents,advertisers(name)").eq("organization_id",organizationId).eq("campaign_id",campaignId).in("status",["held","reserved","confirmed"])]);
 const c=requireQueryData("campaign detail",cr),slots=requireQueryData("campaign slots",sr),advertiserRows=requireQueryData("campaign advertisers",ar),placements=requireQueryData("campaign placements",pr);if(!c)notFound();const advertisers=canManage&&c.status==="selling"?advertiserRows:[];const bySlot=new Map(placements.map(p=>[p.campaign_slot_id,p]));const projected=placements.reduce((n,p)=>n+p.sale_price_cents,0);
 return <><ApplicationHeader title={c.name} eyebrow={c.territory}/><PageContainer><section className="grid gap-4 rounded-2xl border bg-white p-5 sm:grid-cols-3"><div><p className="text-xs text-slate-500">Publication</p><p className="font-bold">{c.publication_date}</p></div><div><p className="text-xs text-slate-500">Inventory</p><p className="font-bold">{slots.filter(s=>s.status==="available").length} available · {slots.filter(s=>s.status==="reserved").length} reserved</p></div><div><p className="text-xs text-slate-500">Projected revenue</p><p className="font-bold">{formatCurrency(projected)}</p></div></section><section><h2 className="mb-3 text-xl font-bold">Campaign slots</h2><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{slots.map(s=>{const p=bySlot.get(s.id);return <article key={s.id} className="rounded-2xl border bg-white p-5"><div className="flex justify-between gap-3"><div><h3 className="font-bold">{s.identifier}</h3><p className="text-sm text-slate-500">{s.side_or_section}</p></div><span className="h-fit rounded-full bg-slate-100 px-2 py-1 text-xs font-bold capitalize">{s.status}</span></div>{p?<div className="mt-4 text-sm"><p>Advertiser: <strong>{(p.advertisers as unknown as {name:string})?.name}</strong></p><p>Sale price: <strong>{formatCurrency(p.sale_price_cents)}</strong></p></div>:advertisers.length?<ReserveForm campaignId={campaignId} slotId={s.id} price={s.standard_price_cents} advertisers={advertisers}/>:canManage?<p className="mt-4 text-sm text-amber-700">Create an advertiser before reserving.</p>:null}</article>})}</div></section></PageContainer></>;
}
